### ISSUE TITLE
compute button not working

### ISSUE THREAD

**Issue by dbrakenhoff** [Deltares/QGIS-Tim#95]
The server won't start with the following error:
![image](https://user-images.githubusercontent.com/6552225/227188738-fee419a6-4e6d-4979-ba81-dcbc3a9e7266.png)

I'm on ubuntu 22.04 with QGIS 3.28 and the latest version of the QGIS-TIM plugin (I think). 

Fix in server_handler.py, separate the arguments in the call to `subprocess.Popen` (see below) or perhaps add `shell=True` to the command:

```python
        self.process = subprocess.Popen(
            [f"{interpreter}", "-u", "-m", "gistim", "serve"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=env_vars[interpreter],
            text=True,  
        )
```

**Comment by MattBrst** [comment]
We are encoutering a similar issue on Win10 with QGIS 3.28 and the latest plugin: 

![image](https://github.com/Deltares/QGIS-Tim/assets/41747007/5abd616e-2fb4-44db-8d62-43911b65ceaf)

**Comment by Huite** [comment]
I think your reason might be different than Davíd's, because I think his his issue was specific to Ubuntu (and probably linux in general).

You could check %APPDATA%\qgis-tim\.

There should be two JSON files there, which tell the plugin where to find the Python interpreter and what environmental variables to use.

If the directory doesn't exist or is empty, you should (re-)run `python gistim -m configure` which will generate the JSON files.

**Comment by MattBrst** [comment]
Thanks, we solved the problem with your suggestions!

Both JSON files existed in the given folder. We had to change the first entry of both JSON files (which pointed to a personal folder) to the following string; `"C:\\ProgramData\\deltaforge\\python.exe"`
